#!/usr/bin/env python3
# vim: set expandtab tabstop=4 shiftwidth=4:

# Unique Armor Names SSE (SkyPatcher) Generation Script
# Copyright (C) 2026 CJ Kucera 
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#     * Neither the name of the development team nor the
#       names of its contributors may be used to endorse or promote products
#       derived from this software without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL CJ KUCERA BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# This script processes a "source" file of SkyPatcher armor-name-setting
# statements and outputs a version which appends numeric suffixes to groups
# of otherwise-identically-named armor.  For instance, a source file containing
# this:
#
#    filterByArmors=Skyrim.esm|0F1229:fullName=~Clothes~
#    filterByArmors=Skyrim.esm|06C1DA:fullName=~Clothes~
#    filterByArmors=Skyrim.esm|06C1D9:fullName=~Clothes~
#    filterByArmors=Skyrim.esm|06C1D8:fullName=~Clothes~
#    filterByArmors=Skyrim.esm|017695:fullName=~Clothes~
#    filterByArmors=Skyrim.esm|03452E:fullName=~Clothes~
#    filterByArmors=Skyrim.esm|0261C0:fullName=~Clothes~
#    filterByArmors=Skyrim.esm|0209A6:fullName=~Clothes~
#
# ... will generate the following:
#
#    filterByArmors=Skyrim.esm|017695:fullName=~Clothes: 1 of 8~
#    filterByArmors=Skyrim.esm|0209A6:fullName=~Clothes: 2 of 8~
#    filterByArmors=Skyrim.esm|0261C0:fullName=~Clothes: 3 of 8~
#    filterByArmors=Skyrim.esm|03452E:fullName=~Clothes: 4 of 8~
#    filterByArmors=Skyrim.esm|06C1D8:fullName=~Clothes: 5 of 8~
#    filterByArmors=Skyrim.esm|06C1D9:fullName=~Clothes: 6 of 8~
#    filterByArmors=Skyrim.esm|06C1DA:fullName=~Clothes: 7 of 8~
#    filterByArmors=Skyrim.esm|0F1229:fullName=~Clothes: 8 of 8~
#
# Note that it ends up sorting by FormID.  Duplicates in the source file
# are fine, and in fact expected, so don't worry about identical lines in there.
#
# The source file is intended to have been generated by my xEdit script
# `Generate_SkyPatcher_Armor_Name_Statements.pas`, though really it could have
# been generated by anything.
#
# By default, the output file will *only* include SkyPatcher statements for
# armor which "needs" the numeric suffixes, so it will filter the source
# file quite a bit.  You can optionally use the --all argument to output
# all statements instead, which will effectively "pass through" any name
# which doesn't need numbering.
#
# The --mark argument can be used to additionally "mark" all names with an
# asterisk suffix.  I personally end up using that (along with --all) to
# manually keep track of armor that I've collected, since I always like having
# "one of each" in a container somewhere.  That's a rather niche purpose,
# though.
#


import os
import re
import sys
import argparse
import textwrap


def process_skypatcher(source_file, dest_file, output_all=False, do_mark=False, version=None):
    """
    Processing script!  Read from `source_file` and write to `dest_file`.
    If a `version` string is passed in, a header will be written out to
    the destination file which includes the specified version number.
    """

    # Items which will show up as part of a group but the player will
    # only ever get one version (ie: quest rewards and such).  Don't
    # actually process these!
    enumerate_blocklist = {
            "Amulet of Articulation",
            "Fjola's Wedding Band",
            "Mage's Circlet",
            "Miraak",
            "Miraak's Robes",
            "Nightingale Armor",
            "Nightingale Boots",
            "Nightingale Gloves",
            "Nightingale Hood",
            "Shield of Solitude",
            }

    # Regex to read the names
    name_re = re.compile(r"""
        ^
        filterByArmors=
        (?P<filename>.+?)
        \|
        (?P<formid>[0-9A-F]+?)
        :fullName=~
        (?P<name>.+?)
        ~
        \s*
        $
        """, re.X|re.I)

    # Sorting "helper" for identifiers; would like to make sure that base-game
    # items get numbered first, etc.  Because the xEdit script is processing the
    # files in order, we'll be able to naturally construct this as we loop through.
    sort_helper = {}

    name_registry = {}

    with open(source_file) as df:
        for line in df:
            line = line.strip()
            if match := name_re.match(line):
                filename = match.group('filename')
                formid = match.group('formid')
                name = match.group('name')

                if filename not in sort_helper:
                    sort_helper[filename] = len(sort_helper)

                if name not in name_registry:
                    name_registry[name] = set()
                name_registry[name].add((sort_helper[filename], f'{filename}|{formid}'))
            else:
                print('WARNING: line was not understood: {line}')

    with open(dest_file, 'w', newline="\r\n") as odf:

        # Write out a header if we've been told to
        if version:
            header = f'Unique Armor Names SSE (SkyPatcher) v{version}'
            print(textwrap.dedent("""
                    ;;; {header}
                    ;;; {header_underline}
                    ;;;
                    ;;; Adds numeric suffixes to groups of armor/clothing which otherwise
                    ;;; have identical names, so that they're easily distinguishable in
                    ;;; inventory.  (And don't jump around in the list as they're sold or
                    ;;; moved around!)
                    ;;;
                    ;;; by Apocalyptech / https://apocalyptech.com/contact.php
                    ;;; https://github.com/apocalyptech/apocalyptech-skyrim-mods/
                    ;;;
                    ;;; Released under CC BY-SA 4.0 (Attribution-ShareAlike 4.0 International)
                    ;;; https://creativecommons.org/licenses/by-sa/4.0/
                    """.format(
                        header=header,
                        header_underline='='*len(header),
                        )), file=odf)

        if do_mark:
            mark = '*'
        else:
            mark = ''

        for name, identifiers in sorted(name_registry.items()):
            if len(identifiers) == 1:
                if output_all:
                    print(f'filterByArmors={identifiers.pop()[1]}:fullName=~{name}{mark}~', file=odf)
            else:
                length = len(identifiers)
                for idx, (_, identifier) in enumerate(sorted(identifiers)):
                    if name in enumerate_blocklist:
                        if output_all:
                            print(f'filterByArmors={identifier}:fullName=~{name}{mark}~', file=odf)
                    else:
                        print(f'filterByArmors={identifier}:fullName=~{name}: {idx+1} of {length}{mark}~', file=odf)

    print('')
    print(f'Wrote to: {dest_file}')


if __name__ == '__main__':

    parser = argparse.ArgumentParser(
            description="""Generate a SkyPatcher mod to add a numeric "x of y" suffix
                        to any armor/clothing with multiple of the same name""",
            formatter_class=argparse.ArgumentDefaultsHelpFormatter,
            )

    parser.add_argument(
            '-s', '--source',
            type=str,
            default='Unique_Armor_Names_SSE.source',
            help='Source file to process',
            )

    parser.add_argument(
            '-d', '--dest',
            type=str,
            default='../SKSE/Plugins/SkyPatcher/armor/Unique_Armor_Names_SSE.ini',
            help='Destination file to write to',
            )

    parser.add_argument(
            '-a', '--all',
            action='store_true',
            help="Include *all* armor names, even if there aren't duplicates",
            )

    parser.add_argument(
            '-m', '--mark',
            action='store_true',
            help="Mark all armor names with an asterisk suffix at the end",
            )

    parser.add_argument(
            '-f', '--force',
            action='store_true',
            help='Force overwrite, if the destination file already exists',
            )

    parser.add_argument(
            '-v', '--version',
            type=str,
            help='Adds a version header to the top of the generated file',
            )

    args = parser.parse_args()

    if not args.force and os.path.exists(args.dest):
        resp = input(f'Destination file {args.dest} already exists, overwrite? [y/N]> ').strip()
        if len(resp) == 0 or resp[0].lower() != 'y':
            print('Exiting!')
            sys.exit(1)

    process_skypatcher(args.source, args.dest, output_all=args.all, do_mark=args.mark, version=args.version)

