#!/usr/bin/env python3
# vim: set expandtab tabstop=4 shiftwidth=4:

import os
import re
import sys
import argparse

# Book Sorting SSE (SkyPatcher) Generation Script
# Copyright (C) 2026 CJ Kucera 
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#     * Neither the name of the development team nor the
#       names of its contributors may be used to endorse or promote products
#       derived from this software without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL CJ KUCERA BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# This script processes a "source" file of SkyPatcher book-title-setting
# statements and outputs a normalized version of the file.  For instance, a
# source file which starts out like so:
#
#     ; Skyrim
#     filterByBooks=Skyrim.esm|01ACD4:fullName=~Mysterious Akavir~
#     filterByBooks=Skyrim.esm|01ACD5:fullName=~Gods and Worship~
#     filterByBooks=Skyrim.esm|01ACD6:fullName=~The Real Barenziah, Vol. 1~
#     filterByBooks=Skyrim.esm|01ACD7:fullName=~The Real Barenziah, Vol. 2~
#
# ... would end up getting processed into this:
#
#     ; Skyrim
#     filterByBooks=Skyrim.esm|01ACD6:fullName=~Real Barenziah, The (Vol. 1)~
#     filterByBooks=Skyrim.esm|01ACD7:fullName=~Real Barenziah, The (Vol. 2)~
#
# The source file is intended to have been generated by my xEdit script
# `Generate_SkyPatcher_Book_Name_Statements.pas`, though really it could have
# been generated by anything.
#
# The goal is to "normalize" book titles such that (nearly) everything will
# be automatically alphabetized properly in-game.  It also tries to apply the
# same kind of normalizations that were done as part of USSEP, and also the
# "Book Covers Skyrim" mod, which among other things normalizes the display of
# the volume or part numbers.  This script will end up applying its own version
# of the volume/part/book numbers by putting those in praentheses, for the most
# part.  Book titles which are unchanged by this processing are omitted
# entirely from the output.  Lines which are *not* book-title-setting statements
# are passed through unchanged.
#
# The most obvious effect is moving the initial article (the/a/an) to the back
# of the title, so the game's built-in alphabetization can do its thing.  That
# does end up posing some stylistic challenges in some cases, such as when
# there are multiple volumes.  For instance, here's some possible
# normalizations of "The Real Barenziah, Vol. 2":
#
#    - Real Barenziah, Vol. 2, The
#    - Real Barenziah, The, Vol. 2
#    - Real Barenziah, The (Vol. 2)
#
# To my eyes, the only one which looks good at all is the one which uses
# parentheses, so that's what I went with.  And, since I was doing that for
# the multi-volume books, I figured it would be good to apply that same
# normalization to other multi-volume books in the game, whether or not they
# had a leading article.  So "Brief History of the Empire, Vol. 1" becomes
# "Brief History of the Empire (Vol. 1)".
#
# Note that I've written this based on book titles that have already been
# normalized somewhat by either USSEP or Book Covers Skyrim, so you won't
# necessarily get the same output if you start with the book covers from the
# vanilla game.  For instance in the vanilla game there's a "Feyfolken II"
# but Book Covers Skyrim normalized that to "Feyfolken, Vol. 2".  If you
# run the script against a file with the original title, it'll remain
# untouched, but if you run it against a file generated from Book Covers
# Skyrim, it'll get normalized to "Feyfolken (Vol. 2)".
#
# I've made some token efforts to support some of the pre-USSEP/pre-Book-
# Covers-Skyrim titles found in the vanilla game.  For instance "Butcher
# Journal #1" should get normalized to "Butcher Journal (Part 1)", but
# the script hasn't really been tested against the vanilla titles to see
# if there are any gaps in processing.  (The Book Covers Skyrim version
# of that title would become "Journal - Butcher's (Part 1)" with this
# script.)
#
# "Volume" type titles that we do *not* touch:
#
#  - The "2920" series.  Those all have subtitles and the names we already
#    have are just fine.  (IMO any edit we make would make 'em look weird)
#
#  - The vanilla titles of some book series use roman numerals, which wouldn't
#    get processed by this script.  A few (probably non-exhaustive) examples:
#    - 16 Accounts of Madness
#    - Feyfolken
#    - Rising Threat
#    - Treasure Maps (I'd probably want to leave those alone anyway)
#
# Hardcoded exceptions:
#
#  - "A Kiss, Sweet Mother" is being left alone, since it'd look weird no
#    matter what we did to it.
#
# Other edits:
#
#  - The quotes are being taken out of '"Madmen" of the Reach', so that it
#    alphabetizes into the Ms properly.


def process_skypatcher(source_file, dest_file, version=None):
    """
    Processing script!  Read from `source_file` and write to `dest_file`.
    If a `version` string is passed in, a header will be written out to
    the destination file which includes the specified version number.
    """

    # Regex to pull the title apart
    name_re = re.compile(r"""
        ^                                    # Line beginning
        (?P<begin>filterByBooks.*?fullName=) # Everything up to the tilde quote
        ~                                    # Beginning tilde quote
        (?P<title>.*?)                       # Initial title (might end up being the whole thing, if there's no volume)
        (                                    # Start of looking for optional "volume" identifiers
            (,\ |\ -\ |\ )                   # Possible delineations
            (?P<indicator>                   # Possible indicators of "volume"
                vol\.?\ 
                |
                volume\ 
                |
                v
                |
                book\ 
                |
                part\ 
                |
                #
            )
            (?P<volume>\d+)                  # The actual volume number itself
        )?
        ~                                    # Ending tilde quote
        \s*                                  # Optional ending whitespace (though should be stripped by this point)
        $                                    # Line end
        """, re.X|re.I)

    prefixes = [
            'the ',
            'a ',
            'an ',
            ]

    with open(source_file) as df:
        with open(dest_file, 'w', newline="\r\n") as odf:

            # Write out a header if we've been told to
            if version:
                header = f'Book Sorting SSE (SkyPatcher) v{version}'
                print(f'; {header}', file=odf)
                print('; {}'.format('='*len(header)), file=odf)
                print(';', file=odf)
                print('; by Apocalyptech / https://apocalyptech.com/contact.php', file=odf)
                print('; https://github.com/apocalyptech/apocalyptech-skyrim-mods/', file=odf)
                print(';', file=odf)
                print('; Released under CC BY-SA 4.0 (Attribution-ShareAlike 4.0 International)', file=odf)
                print('; https://creativecommons.org/licenses/by-sa/4.0/', file=odf),
                print(';', file=odf)
                print('; Generated based on book titles extracted from:', file=odf)
                print(';  - Book Covers Skyrim - USSEP Update', file=odf)
                print(';    https://www.nexusmods.com/skyrimspecialedition/mods/50615', file=odf)
                print(';  - Saints and Seducers (ccBGSSSE025-AdvDSGS.esm)', file=odf)
                print(';  - Fishing Creation (ccBGSSSE001-Fish.esm)', file=odf)
                print('', file=odf)

            for line in df:
                line = line.strip()
                if match := name_re.match(line):
                    begin = match.group('begin')
                    title = match.group('title')
                    indicator = match.group('indicator')
                    volume = match.group('volume')
                    new_title = title

                    # Move the prefix, if we have one (and apply a couple of hardcoded
                    # actions)
                    found_prefix = False
                    for prefix in prefixes:
                        if title.casefold().startswith(prefix):
                            found_prefix = True
                            
                            # Hardcoded exception: this one just looks too weird with
                            # the article at the end
                            if title == 'A Kiss, Sweet Mother':
                                break

                            # Swap the article to the back
                            new_title = title[len(prefix):] + ', ' + title[:len(prefix)-1]

                            # Another hardcoded exception!
                            if new_title.startswith('"Madmen"'):
                                new_title = 'Madmen' + new_title[8:]

                            break

                    # Add in the volume, if we have one
                    if volume:
                        match indicator[0].lower():
                            case 'b':
                                new_title += ' (Book ' + volume + ')'
                            case 'p' | '#':
                                new_title += ' (Part ' + volume + ')'
                            case _:
                                new_title += ' (Vol. ' + volume + ')'

                    # Write out the new title, if we have changes
                    if title != new_title:
                        print(f'{begin}~{new_title}~', file=odf)
                    else:
                        print(f'NOTICE: No changes found for "{title}"')

                else:
                    print(line, file=odf)

    print('')
    print(f'Wrote to: {dest_file}')


if __name__ == '__main__':

    parser = argparse.ArgumentParser(
            description='Normalize book titles in SkyPatcher statements',
            formatter_class=argparse.ArgumentDefaultsHelpFormatter,
            )

    parser.add_argument(
            '-s', '--source',
            type=str,
            default='Book_Sorting_SSE_SkyPatcher.source',
            help='Source file to process',
            )

    parser.add_argument(
            '-d', '--dest',
            type=str,
            default='../SKSE/Plugins/SkyPatcher/book/Book_Sorting_SSE_SkyPatcher.ini',
            help='Destination file to write to',
            )

    parser.add_argument(
            '-f', '--force',
            action='store_true',
            help='Force overwrite, if the destination file already exists',
            )

    parser.add_argument(
            '-v', '--version',
            type=str,
            help='Adds a version header to the top of the generated file',
            )

    args = parser.parse_args()

    if not args.force and os.path.exists(args.dest):
        resp = input(f'Destination file {args.dest} already exists, overwrite? [y/N]> ').strip()
        if len(resp) == 0 or resp[0].lower() != 'y':
            print('Exiting!')
            sys.exit(1)

    process_skypatcher(args.source, args.dest, version=args.version)

